[BITS 16]
ORG 0

mov ax,0x0050
mov ds,ax
mov es,ax
mov fs,ax

mov al,'$'
mov ah,0xE
int 0x10

mov si,msg
call Print
jmp $

msg db "Hello world\nThe code page stored in ROM is also called the hardware code page. In Western PCs it typically defaults to code page 437, but various Eastern European PCs used a number of other code pages as hardware code page, sometimes user-selectable via jumpers or CMOS setup. Arabic and Hebrew PCs and printers even supported multiple software-switchable hardware code pages, also named font pages."
    db "The original IBM PC contained this font as a 9×14 pixels-per-character font stored in the ROM of the IBM Monochrome Display Adapter (MDA) and an 8×8 pixels-per-character font of the Color Graphics Adapter (CGA) cards. The IBM Enhanced Graphics Adapter (EGA) contained an 8×14 pixels-per-character version, and the VGA contained a 9×16 version.All these display adapters have text modes in which each character cell contains an 8-bit character code point (see details), giving 256 possible values for graphic characters. All 256 codes were assigned a graphical character in ROM, including the codes from 0 to 31 that were reserved in ASCII for non-graphical control characters."
	db "\nA legacy of code page 437 and other DOS codepages is the set of number combinations used in Windows Alt keycodes introduced in the first versions of MS-DOS. The user could enter a character by holding down the Alt key and entering the three-digit decimal Alt keycode on the numpad. When Microsoft switched to more standard character sets (such as CP1252 and later Unicode) in Windows, so many users had memorized the numbers used by their DOS codepage that Microsoft had to retain the original codes (they added the ability to type a code in the current character set by typing the numpad 0 before the digits)"
	db "\nThe first cluster of the data area is cluster #2. That leaves the first two entries of the FAT unused. In the first byte of the first entry a copy of the media descriptor is stored. The remaining bits of this entry are 1. In the second entry the end-of-file marker is stored. The high order two bits of the second entry are sometimes, in the case of FAT16 and FAT32, used for dirty volume management: high order bit 1: last shutdown was clean; next highest bit 1: during the previous mount no disk I/O errors were detected."
	db "The first byte of a name must not be 0x20 (space). Short names or extensions are padded with spaces. Special ASCII characters 0x22 ('), 0x2a (*), 0x2b (+), 0x2c (,), 0x2e (.), 0x2f (/), 0x3a (:), 0x3b (;), 0x3c (<), 0x3d (=), 0x3e (>), 0x3f (?), 0x5b ([), 0x5c (\), 0x5d (]), 0x7c (|) are not allowed. "
	db "In Windows 95 a variation was introduced: VFAT. VFAT (Virtual FAT) is FAT together with long filenames (LFN), that can be up to 255 bytes long. The implementation is an ugly hack. These long filenames are stored in special directory entries. A special entry looks like this: "
	db "The short name is derived from the long name as follows: The extension is the extension of the long name, truncated to length at most three. The first six bytes of the short name equal the first six nonspace bytes of the long name, but bytes +,;=[], that are not allowed under DOS, are replaced by underscore. Lower case is converted to upper case. The final two (or more, up to seven, if necessary) bytes become ~1, or, if that exists already, ~2, etc., up to ~999999. OK :)"
	db "The licenses for most software are designed to take away your"
	db "freedom to share and change it.  By contrast, the GNU General Public"
	db "License is intended to guarantee your freedom to share and change free"
	db "software--to make sure the software is free for all its users.  This"
	db "General Public License applies to most of the Free Software"
	db "Foundation's software and to any other program whose authors commit to"
	db "using it.  (Some other Free Software Foundation software is covered by"
	db "the GNU Library General Public License instead.)  You can apply it to"
	db "your programs, too."

	db "  When we speak of free software, we are referring to freedom, not"
	db "price.  Our General Public Licenses are designed to make sure that you"
	db "have the freedom to distribute copies of free software (and charge for"
	db "this service if you wish), that you receive source code or can get it"
	db "if you want it, that you can change the software or use pieces of it"
	db "in new free programs; and that you know you can do these things."

	db "  To protect your rights, we need to make restrictions that forbid"
	db "anyone to deny you these rights or to ask you to surrender the rights."
	db "These restrictions translate to certain responsibilities for you if you"
	db "distribute copies of the software, or if you modify it."

	db "  For example, if you distribute copies of such a program, whether"
	db "gratis or for a fee, you must give the recipients all the rights that"
	db "you have.  You must make sure that they, too, receive or can get the"
	db "source code.  And you must show them these terms so they know their"
	db "rights."

	db "  We protect your rights with two steps: (1) copyright the software, and"
	db "(2) offer you this license which gives you legal permission to copy,"
	db "distribute and/or modify the software."

  	db "Also, for each author's protection and ours, we want to make certain"
	db "that everyone understands that there is no warranty for this free"
	db "software.  If the software is modified by someone else and passed on, we"
	db "want its recipients to know that what they have is not the original, so"
	db "that any problems introduced by others will not reflect on the original"
	db "authors' reputations."

	db "  Finally, any free program is threatened constantly by software"
	db "patents.  We wish to avoid the danger that redistributors of a free"
	db "program will individually obtain patent licenses, in effect making the"
	db "program proprietary.  To prevent this, we have made it clear that any"
	db "patent must be licensed for everyone's free use or not licensed at all."
	db "AVAST END USER LICENSE AGREEMENT(FREE VERSION)PLEASE READ THE TERMS AND CONDITIONS OF THIS LICENSE AGREEMENT (“AGREEMENT”) CAREFULLY BEFORE USING THE SOFTWARE (AS DEFINED BELOW). THIS IS A LEGALLY BINDING CONTRACT BETWEEN YOU AND AVAST SOFTWARE a.s., A COMPANY DULY ORGANIZED AND EXISTING UNDER THE LAWS OF THE CZECH REPUBLIC, REGISTERED IN THE COMMERCIAL REGISTER MAINTAINED BY THE MUNICIPAL COURT IN PRAGUE IN SECTION B, INSERT NO. 11402 (“AVAST”). BY ASSENTING ELECTRONICALLY, INSTALLING OR USING THIS SOFTWARE YOU ACCEPT ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT.  If you do not agree with the terms and conditions of this Agreement, do not continue the installation process and delete or destroy all copies of the Software in your possession. This Agreement accompanies certain software (including any upgrades or updates thereto as provided by AVAST, the “Software”) and related explanatory written materials (the “Documentation”). 1.	LicenseAVAST grants to you a non-exclusive perpetual license to use the Software and the Documentation for so long as AVAST makes the Software available, provided that you agree to the terms and conditions of this Agreement. 2.	Permitted Use of the SoftwareYou"
	db " may install and use the Software on an unlimited number of computers. The Software must be used exclusively by you or members of your household solely for private non-commercial purposes. You may also make one backup copy of the Software.ANY USE OF THE SOFTWARE OTHER THAN AS EXPRESSLY AUTHORIZED BY THIS SECTION OR ANY RESALE OR FURTHER DISTRIBUTION OF THE SOFTWARE CONSTITUTES A MATERIAL BREACH OF THIS AGREEMENT AND MAY VIOLATE APPLICABLE COPYRIGHT LAWS.3."
	db "	Upgrades and UpdatesUpgrades and updates of the Software shall be provided to you by AVAST as long as and to the extent in which AVAST in its exclusive discretion makes such upgrades and updates available to the users of the free version of the Software.4.	Ownership RightsThe Software and Documentation is the intellectual property of AVAST and is protected by applicable copyright laws, international treaty provisions and other applicable laws of the country in which the Software is being used. The structure, organization and code of the Software are valuable trade secrets and confidential information of AVAST. To the extent you provide any comments or suggestions about the Software to AVAST, AVAST shall have the right to retain and use any such comments or suggestions in our current or future products or services, without further compensation to you and without your approval of such retention or use.Except as stated in this Agreement, your possession, installation and use of the Software does not grant you any rights or title to any intellectual property rights in the Software or Documentation. All rights to the Software and Documentation, including all associated copyrights, patents, trade secret rights, trademarks and other intellectual property rights, are reserved by AVAST. 5.	 RestrictionsYou may not copy or use the Software or the Documentation except as set forth in Section 2 of this Agreement. You may not remove any proprietary notices or labels on the Software;"
	db " any copies that you are permitted to make pursuant to this Agreement must contain the same copyright and other proprietary notices that appear on and in the Software. You agree not to modify, adapt, translate, reverse engineer, decompile or disassemble the Software or otherwise attempt to discover the source code of the Software or algorithms contained therein or create any derivative works from the Software. You are not permitted to use the Software in connection with the provision of any commercial services which include"
	db " processing or transferring the data of or for other persons or entities (“Data”), including cloud computing and “Software as a Service” solutions, providing storage capacities for Data; transmitting, routing of or providing connection to Data, or providing information search tool services. You may not permit third parties to benefit from the use or functionality of the Software via a timesharing, service bureau or other similar arrangement.6.	TransferYou may not rent, lease, sub-license, or lend the Software or the Documentation or any portions thereof. You may, however, transfer all your rights to use the Software and the Documentation to another person provided that (i) the transferee accepts the terms of this Agreement; (ii) you transfer the Software, including all copies, updates and prior versions, and all Documentation to such person; and (iii) you retain no copies of the Software or of the Documentation, including but not limited to copies stored on your computer. Partial transfer of your rights under this Agreement is strictly prohibited. 7.	Disclaimers and Exclusion of LiabilityBe aware that the Software may make changes to your computer "
	db "that may adversely affect its functionality, such as deleting system or application files identified (correctly or incorrectly) by the Software as infected. You acknowledge and agree to such changes to your computer that may occur as a result of your use of the Software. The Software is not fault-tolerant and as such is not designed for use in hazardous environments requiring fail-safe performance.AVAST AND ITS DISTRIBUTORS DO NOT AND CANNOT WARRANT THE PERFORMANCE OR RESULTS YOU MAY OBTAIN BY USING THE SOFTWARE OR DOCUMENTATION. THE REMEDY IN THIS SECTION STATES THE SOLE AND EXCLUSIVE REMEDIES FOR AVAST'S OR ITS DISTRIBUTORS’ OR AGENTS’ BREACH OF WARRANTY. THE SOFTWARE IS PROVIDED “AS IS” AND AVAST AND ITS DISTRIBUTORS MAKE NO EXPRESS OR IMPLIED WARRANTIES OR CONDITIONS AND, TO THE MAXIMUM EXTENT PERMITTED BY LAW, DISCLAIM ANY AND ALL CONDITIONS AND WARRANTIES IMPLIED BY STATUTE, COMMON LAW OR JURISPRUDENCE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF NONINFRINGEMENT OF THIRD PARTY RIGHTS, MERCHANTABILITY, SUITABLE QUALITY OR FITNESS FOR ANY PARTICULAR PURPOSE.YOU AGREE AND ACCEPT THAT, TO THE FULL EXTENT PERMITTED BY LAW, IN NO EVENT WILL AVAST OR ITS DISTRIBUTORS OR AGENTS BE LIABLE TO YOU FOR ANY DAMAGES, ESPECIALLY FOR CONSEQUENTIAL, INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS, LOST SAVINGS OR LOST DATA, EVEN IF AVAST OR ITS DISTRIBUTOR OR AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF "
	db "SUCH DAMAGES, OR FOR ANY CLAIM BY ANY THIRD PARTY. TO THE FULL EXTENT PERMITTED BY LAW, YOU AGREE AND ACCEPT THAT IN NO CASE SHALL AVAST’S OR ITS DISTRIBUTORS’ "
	db "OR AGENTS LIABILITY FOR ANY DAMAGE EXCEED THE LESSER OF FIVE U.S. DOLLARS ($5.00) OR THE AMOUNT OF THE ONE YEAR"
	db " LICENSE FEE FOR AVAST’S COMMERCIAL PRODUCT CLOSEST TO YOUR FREE VERSION OF THE SOFTWARE."
	db "THE FOREGOING EXCLUSIONS AND LIMITATIONS OF LIABILITY OF AVAST AND ITS DISTRIBUTORS DO NOT LIMIT POTENTIAL LIABILITY FOR DEATH, PERSONAL INJURY OR FRAUD OVER THE EXTENT PERMITTED BY APPLICABLE LAWS.8.	Privacy; Processing of Personal InformationThe Software automatically and from time to time may collect certain information, which may include personally identifiable information, from the computer on which it is installed, including:8.1	URLs of visited websites that the Software identifies as potentially infected, together with the information on the nature of identified threats (e.g. viruses, Trojans, tracking cookies and any other forms of malware) and URLs of several sites visited before the infection was identified to ascertain the source of the infection;8.2	Information and files (including executable files) on your computer identified by the Software as potentially infected, together with the information about the nature of identified threats;8.3	Information about the sender and subject of emails identified by the Software as potentially infected, together with the information on the nature of identified threats;8.4	Information contained in emails reported by you as spam or as incorrectly identified as spam by the Software;8.5	Copies of the files identified by the Software as potentially infected or parts thereof may be automatically sent to AVAST for further examination and analysis;8.6	Certain information"
	db " about your computer hardware, software and/or network connection;8.7	Certain information about the installation and operation of the Software and encountered errors or problems;8.8	Statistical information about threats detected by the Software; an8.9	If your version of the Software includes the Website reputation function, which provides information on reputation of web sites as potential sources of malware, and you set the Website reputation function to active,"
	db " the Software may send AVAST the URLs of all websites you want to visit and the results of your web searches through search engines."
	db " The information collected by the Software is generally not correlated with any other personal information related to you that AVAST may be processing such as information given by you to AVAST or its distributors or agents during the process of ordering and downloading the Software. Unless you have permitted otherwise, the information collected by the Software is used anonymously in aggregation with similar information from other users of the Software for analytical purposes to identify new viruses and threats and for improvement and development of the Software and for statistical purposes.By using the Software you acknowledge and agree that AVAST or its distributors or agents may collect and use the information as described above. You are giving this consent on behalf of all users of all computers where the Software will be used under this license and you accept full responsibility for informing all users and acquiring their fully informed, free and valid consent with processing of their personal information by the Software as described above.Notwithstanding anything to the contrary in the AVAST privacy policy, you consent during the term of this Agreement and for one (1) year thereafter to (i) AVAST sharing information collected by you during your installation or registration of the Software with AVAST’s distributors and other business partners and (ii) use of such information by AVAST, its distributors and other business partners to present you with information that may be relevant to you, including offers of software, services or other products. The collected information may be transferred to third parties or to other countries that may have less protective data protection laws than the country or region in which you are situated (including the European Union). AVAST takes measures to ensure that any collected information will receive an adequate level of protection if and when transferred. Notwithstanding anything to the contrary in"
	db " this Agreement or any Documentation or other materials provided to you in connection with the Software, AVAST reserves all rights to cooperate with any legal process or government inquiry (including, but not limited to, court orders and law enforcement requests) related to your use of the Software. In connection with such cooperation, AVAST may provide documents and information relevant to a court subpoena or government or other legal investigation, which may include disclosure of your personally identifiable information. AVAST may also use statistics derived from the collected information to track and publish reports on security risk trends. By using the Software, you acknowledge and agree that AVAST may collect, transmit, store, disclose and analyze such information for any of the foregoing purposes listed in this Section.9.	 U.S. Government Restricted RightsThis Software and Documentation are deemed to be “commercial computer software” and “commercial computer software documentation”, respectively, and subject to certain restricted rights as identified in FAR Section 52.227-19 Commercial Computer Software  - Restricted Rights and DFARS 227.7202, “Rights in Commercial Computer Software or Commercial Computer Software Documentation”, as applicable, or any successor U.S. regulations. Any use, modification, reproduction, release, performance, display or disclosure of the Software by the U.S. Government shall be done solely in accordance with this Agreement. 10.	Export RegulationsYou agree and accept that the Software and the Documentation may be subject to import and export laws of any country, including those of the United States (specifically the Export Administration Regulations (EAR)) and the European Union. If you transfer or export the Software, which in all cases must be done in accordance with this Agreement, you agree to and acknowledge that you are exclusively responsible for complying with all applicable laws and regulations, including but not limited to all United States and European Union trade sanctions and export regulations"
	db " (including any activities relating to nuclear, chemical or biological materials or weapons, missiles or technology capable of mass destruction), regardless of "
	db "the country in which you reside in or of which you are a citizen. 11.	Governing Law and JurisdictionThe laws of the State of California, excluding its conflicts of law rules, govern this Agreement and your use of the Software and the Documentation. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. The courts located within the county of Santa Clara, California shall be the exclusive jurisdiction and venue for any dispute or legal matter arising out of or in connection with this Agreement or your use of the Software and the Documentation. Notwithstanding this, you agree that AVAST shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction.12.	GeneralThis Agreement is the entire agreement between you and AVAST relating to the Software and Documentation. This Agreement supersedes all prior or contemporaneous oral or written communications, proposals, and representations with respect to the Software or Documentation.  Notwithstanding the foregoing, nothing in this Agreement will diminish any rights you may have under existing consumer protection legislation or other applicable laws in your jurisdiction that may not be waived by contract. This Agreement will immediately terminate upon your breach of any obligation contained herein (especially your obligations in Sections 2, 5, 10) and you shall cease use and destroy all copies of the Software and Documentation in your possession. AVAST reserves the right to any other remedies available under law in the event your breach of this Agreement adversely affects AVAST or its distributors or agents. The limitations of liability and disclaimers of warranty and damages contained herein shall survive termination of this Agreement.  This Agreement may be modified by the Documentation. No provision hereof shall be deemed"
	db " waived unless such waiver shall be in writing and signed by AVAST. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect.If you have any questions regarding this Agreement or wish to request any information from AVAST, please write to AVAST Software, Budejovicka 1518/13A, 140 00 Praha 4, Czech Republic, e-mail: support@avast.com, tel.: +420 274 005 777 or visit our support page at www.avast.com/support."
	db 0
	
Print:
	pusha
		mov ah,0xE
	.lp:
		lodsb
		cmp al,0
		je .done
		int 0x10
		jmp .lp
	.done:
	popa
	ret